"use client";

import { useEffect, useMemo, useRef, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "https://flyway-api.zileslabs.com";
type LiveReport = { id:string; species:string; flock_size:string; behavior:string; zone_latitude:number; zone_longitude:number; confidence:number; occurred_at:string; confirmations:number };
type MapReport = LiveReport & { x:number; y:number; size:number; color:string; age:string };
type Panel = "map" | "activity" | "saved" | "more";
type Filter = "all" | "dabblers" | "divers";
type MapCenter = { lat:number; lon:number };

const labels: Record<string,string> = { mallard:"Mallard",teal:"Teal",gadwall:"Gadwall",pintail:"Pintail",wood_duck:"Wood duck",diver:"Diver",mixed:"Mixed ducks",other:"Other ducks",feeding:"Feeding",circling:"Circling",flying_over:"Flying over",resting:"Resting on water",moving_in:"Moving into area" };
const colors: Record<string,string> = { mallard:"green",teal:"blue",mixed:"gold",gadwall:"gray" };
const speciesValues: Record<string,string> = { Mallard:"mallard",Teal:"teal",Gadwall:"gadwall","Mixed ducks":"mixed" };
const amountValues: Record<string,string> = { "1–10":"1-10","10–25":"10-25","25–50":"25-50","50+":"50+" };

function age(iso:string){ const m=Math.max(1,Math.floor((Date.now()-new Date(iso).getTime())/60000)); return m<60?`${m}m`:`${Math.floor(m/60)}h`; }
function position(n:number, offset:number){ const value=Math.abs(Math.sin(n*997+offset)*10000); return 14+(value-Math.floor(value))*72; }
function project(lat:number,lon:number,zoom:number){const size=256*2**zoom;const safeLat=Math.max(-85.0511,Math.min(85.0511,lat));const sin=Math.sin(safeLat*Math.PI/180);return{x:(lon+180)/360*size,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*size};}
function unproject(x:number,y:number,zoom:number):MapCenter{const size=256*2**zoom;const lon=x/size*360-180;const n=Math.PI-2*Math.PI*y/size;return{lat:180/Math.PI*Math.atan(Math.sinh(n)),lon:((lon+540)%360)-180};}
async function request(path:string, options:RequestInit={}){ const res=await fetch(`${API}${path}`,options); const text=await res.text(); const data=text?JSON.parse(text):null; if(!res.ok) throw new Error(data?.error||"Request failed"); return data; }

export default function Home(){
  const [reports,setReports]=useState<MapReport[]>([]);
  const [selectedId,setSelectedId]=useState("");
  const [loading,setLoading]=useState(true);
  const [panel,setPanel]=useState<Panel>("map");
  const [filter,setFilter]=useState<Filter>("all");
  const [savedIds,setSavedIds]=useState<string[]>([]);
  const [detailId,setDetailId]=useState("");
  const [zoom,setZoom]=useState(4);
  const [center,setCenter]=useState<MapCenter>({lat:39.5,lon:-98.35});
  const [viewport,setViewport]=useState({width:1280,height:720});
  const drag=useRef<{pointerX:number;pointerY:number;centerX:number;centerY:number}|null>(null);
  const [reporting,setReporting]=useState(false);
  const [authOpen,setAuthOpen]=useState(false);
  const [authMode,setAuthMode]=useState<"login"|"signup">("login");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [displayName,setDisplayName]=useState(""); const [authError,setAuthError]=useState("");
  const [token,setToken]=useState(""); const [profile,setProfile]=useState<{display_name:string}|null>(null);
  const [species,setSpecies]=useState("Mallard"); const [amount,setAmount]=useState("25–50"); const [behavior,setBehavior]=useState("feeding"); const [status,setStatus]=useState("");

  const visibleReports=useMemo(()=>reports.filter(r=>filter==="all"||(filter==="divers"?r.species==="diver":r.species!=="diver")),[reports,filter]);
  const savedReports=useMemo(()=>reports.filter(r=>savedIds.includes(r.id)),[reports,savedIds]);
  const selected=useMemo(()=>reports.find(r=>r.id===selectedId)||visibleReports[0],[reports,visibleReports,selectedId]);
  const detail=useMemo(()=>reports.find(r=>r.id===detailId),[reports,detailId]);
  const mapGeometry=useMemo(()=>{const centerPx=project(center.lat,center.lon,zoom);const size=256*2**zoom;const minX=Math.floor((centerPx.x-viewport.width/2)/256)-1,maxX=Math.floor((centerPx.x+viewport.width/2)/256)+1,minY=Math.max(0,Math.floor((centerPx.y-viewport.height/2)/256)-1),maxY=Math.min(2**zoom-1,Math.floor((centerPx.y+viewport.height/2)/256)+1);const tiles=[];for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const wrapped=((x%(2**zoom))+2**zoom)%(2**zoom);tiles.push({key:`${zoom}-${x}-${y}`,url:`https://tile.openstreetmap.org/${zoom}/${wrapped}/${y}.png`,left:x*256-centerPx.x+viewport.width/2,top:y*256-centerPx.y+viewport.height/2});}return{tiles,centerPx,size};},[center,zoom,viewport]);

  async function load(){ try{ const data=await request("/api/sightings"); const mapped=(data.sightings||[]).map((r:LiveReport)=>({...r,x:position(r.zone_latitude,1),y:position(r.zone_longitude,2),size:r.flock_size==="50+"?108:r.flock_size==="25-50"?92:68,color:colors[r.species]||"gray",age:age(r.occurred_at)})); setReports(mapped); if(mapped[0]) setSelectedId(v=>v||mapped[0].id); } finally{setLoading(false);} }
  useEffect(()=>{ load(); const resize=()=>setViewport({width:window.innerWidth,height:window.innerHeight});resize();window.addEventListener("resize",resize);setSavedIds(JSON.parse(localStorage.getItem("flyway_saved")||"[]")); const saved=localStorage.getItem("flyway_session"); if(saved){ const s=JSON.parse(saved); setToken(s.access_token); request("/api/profile",{headers:{Authorization:`Bearer ${s.access_token}`}}).then(setProfile).catch(()=>localStorage.removeItem("flyway_session")); } return()=>window.removeEventListener("resize",resize); },[]);

  function showReport(id:string){ setSelectedId(id); setDetailId(id); setPanel("map"); }
  function openDetail(id:string){ setSelectedId(id); setDetailId(id); }
  function changeZoom(amount:number){ setZoom(current=>Math.min(15,Math.max(2,current+amount))); }
  function resetMap(){ setZoom(4); setCenter({lat:39.5,lon:-98.35}); }
  function locateMe(){navigator.geolocation?.getCurrentPosition(pos=>{setCenter({lat:pos.coords.latitude,lon:pos.coords.longitude});setZoom(8);});}
  function markerPosition(r:MapReport){const point=project(r.zone_latitude,r.zone_longitude,zoom);let dx=point.x-mapGeometry.centerPx.x;if(dx>mapGeometry.size/2)dx-=mapGeometry.size;if(dx<-mapGeometry.size/2)dx+=mapGeometry.size;return{left:dx+viewport.width/2,top:point.y-mapGeometry.centerPx.y+viewport.height/2};}
  function toggleSaved(id:string){ setSavedIds(current=>{ const next=current.includes(id)?current.filter(x=>x!==id):[...current,id]; localStorage.setItem("flyway_saved",JSON.stringify(next)); return next; }); }
  async function authenticate(){ setAuthError(""); try{ const data=await request(`/api/auth/${authMode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,display_name:displayName})}); if(!data.access_token){ setAuthError("Check your email to confirm your account, then sign in."); setAuthMode("login"); return; } localStorage.setItem("flyway_session",JSON.stringify(data)); setToken(data.access_token); const p=await request("/api/profile",{headers:{Authorization:`Bearer ${data.access_token}`}}); setProfile(p); setAuthOpen(false); }catch(e){setAuthError(e instanceof Error?e.message:"Sign in failed");} }
  function openReport(){ if(!token){setAuthOpen(true);return;} setReporting(true); }
  async function submit(){ setStatus("Getting protected location…"); navigator.geolocation.getCurrentPosition(async pos=>{ try{ setStatus("Sharing activity…"); await request("/api/sightings",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({species:speciesValues[species],flock_size:amountValues[amount],behavior,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy_meters:Math.round(pos.coords.accuracy)})}); setStatus("Activity shared. Your exact location stays private."); await load(); setTimeout(()=>{setReporting(false);setStatus("");},1400); }catch(e){setStatus(e instanceof Error?e.message:"Could not share report");} },()=>setStatus("Location permission is required to report activity."),{enableHighAccuracy:true,timeout:12000}); }
  async function confirm(){ if(!token){setAuthOpen(true);return;} if(!selected)return; await request(`/api/sightings/${selected.id}/confirm`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}); await load(); }
  async function logout(){ try{await request("/api/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}});}catch{} localStorage.removeItem("flyway_session");setToken("");setProfile(null);setPanel("map"); }

  const reportList=(items:MapReport[],empty:string)=><div className="activity-list">{items.length?items.map(r=><button className="activity-row" key={r.id} onClick={()=>showReport(r.id)}><span className={`duck-badge ${r.color}`}>⌁</span><span><b>{labels[r.species]}</b><small>{r.flock_size} birds · {labels[r.behavior]}</small></span><span className="row-meta">{r.age}<small>{r.confidence}% confidence</small></span></button>):<div className="panel-empty">{empty}</div>}</div>;

  return <main className="app-shell"><section className="map" aria-label="Duck activity map">
    <header className="topbar"><div className="brand"><div className="brandmark">F</div><div><strong>FLYWAY</strong><span>DUCK ACTIVITY, NOT HUNTING SPOTS</span></div></div><button className="area" onClick={resetMap}><span><small>LIVE WORLD MAP</small>{zoom<=3?"Worldwide duck activity":zoom<=5?"United States activity":`${Math.abs(center.lat).toFixed(1)}°${center.lat>=0?"N":"S"}, ${Math.abs(center.lon).toFixed(1)}°${center.lon>=0?"E":"W"}`}</span></button><div className="weather"><span>◎</span><div><b>Global</b><small>Pan anywhere · Live reports</small></div></div><button className="avatar" onClick={()=>profile?setPanel("more"):setAuthOpen(true)} aria-label={profile?"Open account":"Sign in"}>{profile?.display_name?.slice(0,2).toUpperCase()||"IN"}</button></header>
    {panel==="map"&&<><aside className="filters">{(["all","dabblers","divers"] as Filter[]).map(value=><button key={value} className={`filter ${filter===value?"active":""}`} onClick={()=>setFilter(value)}>{value==="all"?"All ducks":value[0].toUpperCase()+value.slice(1)}</button>)}</aside>
    <div className="map-canvas" onWheel={e=>changeZoom(e.deltaY<0?1:-1)} onPointerDown={e=>{if((e.target as HTMLElement).closest("button"))return;const p=project(center.lat,center.lon,zoom);drag.current={pointerX:e.clientX,pointerY:e.clientY,centerX:p.x,centerY:p.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setCenter(unproject(drag.current.centerX-(e.clientX-drag.current.pointerX),drag.current.centerY-(e.clientY-drag.current.pointerY),zoom))}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>
      <div className="tile-layer">{mapGeometry.tiles.map(tile=><img key={tile.key} src={tile.url} alt="" draggable={false} style={{left:tile.left,top:tile.top}}/>)}</div>
      {visibleReports.map(r=>{const point=markerPosition(r);return <button aria-label={`Open ${labels[r.species]} report, ${r.flock_size} birds`} key={r.id} onClick={()=>openDetail(r.id)} className={`hotspot ${r.color} ${selected?.id===r.id?"selected":""}`} style={{left:point.left,top:point.top,width:r.size,height:r.size}}><span>{r.flock_size}</span></button>})}
      {!loading&&!visibleReports.length&&<div className="empty-map"><b>No fresh sightings here</b><span>Try another filter or share protected activity.</span></div>}
    </div>
    <div className="map-controls" aria-label="Map controls"><button onClick={()=>changeZoom(1)} aria-label="Zoom in">+</button><button onClick={()=>changeZoom(-1)} aria-label="Zoom out">−</button><button className="reset-map" onClick={locateMe} aria-label="Go to my location">⌖</button><button className="world-map" onClick={()=>{setZoom(2);setCenter({lat:20,lon:0})}} aria-label="Show world">◎</button><span>ZOOM {zoom}</span></div><div className="map-attribution">© OpenStreetMap contributors</div>
    {selected&&visibleReports.some(r=>r.id===selected.id)&&<section className="report-card"><div className="report-head"><div className={`duck-badge ${selected.color}`}>⌁</div><div><span className="eyebrow">LIVE ACTIVITY · {selected.age.toUpperCase()} AGO</span><h2>{labels[selected.species]}</h2></div><button className={`save-btn ${savedIds.includes(selected.id)?"saved":""}`} onClick={()=>toggleSaved(selected.id)} aria-label={savedIds.includes(selected.id)?"Remove saved sighting":"Save sighting"}>{savedIds.includes(selected.id)?"★":"☆"}</button><div className="confidence"><b>{selected.confidence}%</b><span>CONFIDENCE</span></div></div><div className="stats"><div><span>ESTIMATED FLOCK</span><strong>{selected.flock_size} birds</strong></div><div><span>BEHAVIOR</span><strong>{labels[selected.behavior]}</strong></div><div><span>CONFIRMED</span><strong className="up">{selected.confirmations} hunters</strong></div></div><div className="privacy"><span><b>Location protected</b>This report is displayed as a randomized activity zone. The hunter’s exact spot is never returned.</span></div><div className="confirm"><span>Seen them too?</span><button className="confirm-btn" onClick={confirm}>✓ Confirm activity</button></div></section>}</>}
    {panel!=="map"&&<section className="content-panel"><div className="panel-head"><div><span className="eyebrow">FLYWAY NETWORK</span><h2>{panel==="activity"?"Recent activity":panel==="saved"?"Saved sightings":"Your account"}</h2></div>{panel==="activity"&&<button onClick={load}>↻ Refresh</button>}</div>{panel==="activity"&&reportList(reports,"No recent reports yet.")}{panel==="saved"&&reportList(savedReports,"Save useful sightings from the map and they’ll appear here on this device.")}{panel==="more"&&<div className="account-card"><div className="account-avatar">{profile?.display_name?.slice(0,2).toUpperCase()||"IN"}</div><h3>{profile?.display_name||"Hunter"}</h3><p>Reports protect exact coordinates by publishing only randomized activity zones.</p><button className="confirm-btn" onClick={logout}>Sign out</button></div>}</section>}
    <nav className="bottom-nav"><button className={panel==="map"?"active":""} onClick={()=>setPanel("map")}><span className="icon">⌖</span>Map</button><button className={panel==="activity"?"active":""} onClick={()=>setPanel("activity")}><span className="icon">≡</span>Activity</button><button className="report-button" onClick={openReport}><span>＋</span>Report ducks</button><button className={panel==="saved"?"active":""} onClick={()=>setPanel("saved")}><span className="icon">☆</span>Saved</button><button className={panel==="more"?"active":""} onClick={()=>profile?setPanel("more"):setAuthOpen(true)}><span className="icon">◌</span>{profile?"Account":"Sign in"}</button></nav>
  </section>
  {detail&&<div className="modal-wrap" onClick={()=>setDetailId("")}><article className="modal detail-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">PROTECTED ACTIVITY ZONE · {detail.age.toUpperCase()} AGO</span><h2>{labels[detail.species]}</h2></div><button onClick={()=>setDetailId("")} aria-label="Close details">×</button></div><div className="detail-hero"><div className={`duck-badge ${detail.color}`}>⌁</div><div><b>{detail.flock_size} birds</b><span>{labels[detail.behavior]}</span></div><div className="detail-confidence"><b>{detail.confidence}%</b><span>confidence</span></div></div><div className="detail-grid"><div><span>REPORTED</span><b>{new Date(detail.occurred_at).toLocaleString()}</b></div><div><span>COMMUNITY</span><b>{detail.confirmations} confirmations</b></div><div><span>LOCATION</span><b>Randomized activity zone</b></div><div><span>SPECIES GROUP</span><b>{detail.species==="diver"?"Diver":"Dabbler / mixed"}</b></div></div><div className="shield"><span>◉</span><div><b>Exact location hidden</b><p>The map displays a randomized zone. The reporting hunter’s exact coordinates, route, and blind are never shown.</p></div></div><div className="detail-actions"><button className={`save-detail ${savedIds.includes(detail.id)?"saved":""}`} onClick={()=>toggleSaved(detail.id)}>{savedIds.includes(detail.id)?"★ Saved":"☆ Save sighting"}</button><button className="confirm-btn" onClick={confirm}>✓ Confirm activity</button></div></article></div>}
  {reporting&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><div><span className="eyebrow">COMMUNITY SIGHTING</span><h2>Report duck activity</h2></div><button onClick={()=>setReporting(false)}>×</button></div><div className="shield"><span>◉</span><div><b>Your location will be blurred</b><p>Hunters receive a randomized activity zone—not your pin, route, or blind.</p></div></div><label>What did you see?</label><div className="choice-grid">{Object.keys(speciesValues).map(s=><button className={species===s?"active":""} onClick={()=>setSpecies(s)} key={s}>{s}</button>)}</div><label>How many?</label><div className="choice-grid four">{Object.keys(amountValues).map(a=><button className={amount===a?"active":""} onClick={()=>setAmount(a)} key={a}>{a}</button>)}</div><label>What were they doing?</label><select value={behavior} onChange={e=>setBehavior(e.target.value)}><option value="feeding">Feeding</option><option value="circling">Circling</option><option value="flying_over">Flying over</option><option value="resting">Resting on water</option><option value="moving_in">Moving into area</option></select><button className="share" onClick={submit}>Share protected report →</button>{status&&<p className="form-status">{status}</p>}</div></div>}
  {authOpen&&<div className="modal-wrap"><div className="modal auth-modal"><div className="modal-head"><div><span className="eyebrow">HUNTER ACCOUNT</span><h2>{authMode==="login"?"Welcome back":"Join Flyway"}</h2></div><button onClick={()=>setAuthOpen(false)}>×</button></div>{authMode==="signup"&&<><label>Display name</label><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Marsh Hunter"/></>}<label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="hunter@example.com"/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 characters minimum"/><button className="share" onClick={authenticate}>{authMode==="login"?"Sign in":"Create account"}</button>{authError&&<p className="form-status error">{authError}</p>}<button className="auth-switch" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"New to Flyway? Create an account":"Already have an account? Sign in"}</button></div></div>}
  </main>;
}
